terraform {
  required_version = ">= 1.14"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
    # Only to read GitHub's OIDC signing certificate chain, so the provider's
    # thumbprint list tracks certificate rotation instead of being pasted in.
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
  }

  # Partial backend config: `bucket` and `region` are supplied at init time
  # from infra/backend.hcl, which is generated by `make tf-init` and
  # gitignored. The bucket name embeds the AWS account id and this repo is
  # public, so it is not committed.
  backend "s3" {
    key          = "landed/main.tfstate"
    encrypt      = true
    use_lockfile = true
  }
}
