"""add indexes for company, title, skills, date_scraped

Closes AUDIT.md §4 (missing DB indexes). Every query pattern flagged there
gets one: GET /jobs's default ORDER BY date_scraped DESC, jobs.py's
func.lower(company) == ... filter (expression index, not just company),
trends.py's GROUP BY company/title, and unnest(skills) across three
trends endpoints (GIN). Non-concurrent CREATE INDEX — fine at current row
counts (~6k), but should switch to postgresql_concurrently=True (inside
op.get_context().autocommit_block()) once the table is large enough that
a brief write lock during index creation would matter.

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-16

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_job_postings_company', 'job_postings', ['company'], unique=False)
    op.create_index('ix_job_postings_company_lower', 'job_postings', [sa.literal_column('lower(company)')], unique=False)
    op.create_index('ix_job_postings_date_scraped', 'job_postings', [sa.literal_column('date_scraped DESC')], unique=False)
    op.create_index('ix_job_postings_skills_gin', 'job_postings', ['skills'], unique=False, postgresql_using='gin')
    op.create_index('ix_job_postings_title', 'job_postings', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_postings_title', table_name='job_postings')
    op.drop_index('ix_job_postings_skills_gin', table_name='job_postings', postgresql_using='gin')
    op.drop_index('ix_job_postings_date_scraped', table_name='job_postings')
    op.drop_index('ix_job_postings_company_lower', table_name='job_postings')
    op.drop_index('ix_job_postings_company', table_name='job_postings')
    # ### end Alembic commands ###
